### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [mnasoft/mnas-graph#1]
Building with SBCL 2.2.4 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 73c2d026e78a075bed0f92ec4920eaa3e2f0e3d1

*mnas-graph* fails to build with the following error:

```
Unhandled TYPE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001C58003}>: The value "13" is not of type LIST

```

*mnas-graph/demos* fails to build with the following error:

```
Unhandled TYPE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001C58003}>: The value "13" is not of type LIST

```

*mnas-graph/docs* fails to build with the following error:

```
Unhandled TYPE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001C58003}>: The value "13" is not of type LIST

```

*mnas-graph/tests* fails to build with the following error:

```
Unhandled TYPE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001C58003}>: The value "13" is not of type LIST

```

[Full log here](http://report.quicklisp.org/2022-05-14/failure-report/mnas-graph.html)

**Comment by mnasoft** [comment]
Please, check once again with the latest commit 703eb94.
